### PR TITLE
Try to update to Julia 1.9

### PR DESCRIPTION
**Pull request by cormullion**
@BenLauwens Hi Ben!

On Discourse we see people try to use ThinkJulia.jl and encounter problems:

- https://discourse.julialang.org/t/build-thinkjulia-fails-on-windows-10-because-unable-to-open-libllvm/86736
- https://discourse.julialang.org/t/using-thinkjulia/98462
- https://discourse.julialang.org/t/importing-thinkjulia/71700

and possibly more people who don't bother to post on Discourse. 

It's a shame that new users get a poor first impression both of Julia and of your excellent work.

I'm suggesting that a fork of ThinkJulia could be a good idea, so that other people could keep it up to date. You could transfer it to somewhere like [JuliaAcademy](https://github.com/JuliaAcademy/). Or you could give someone permission to fork and register an updated version.

This PR makes a version of ThinkJulia.jl that works with the current version of Julia (and removes references to JuliaBox):

Screenshot 2023-05-08 at 14 28 38

I haven't checked the generation of the text though.

### CODE REVIEW

**Review by BenLauwens — APPROVED** [review]

**Comment by BenLauwens** [comment]
I prefer not to transfer this repository. I am working on a complete update. In between I can grant access to volunteers to fix the existing issues. Apparently I cannot merge because there are some conflicts...

**Comment by cormullion** [comment]
Hi! Good to know!

**Comment by cormullion** [comment]
@BenLauwens Thanks, Ben. I'll give it a bit more testing soon.

Any thoughts about registering it in the General registry?

**Comment by BenLauwens** [comment]
Hi

The update will be using Pluto. I have already written a Pluto .jl file convertor to LaTeX to PDF and I plan also to write a Pluto .jl file to HTML (compliant to the format used by O’Reilly). So I was waiting to register ThinkJulia if this was finished but if the existing toolchain can produce the html output, we can register. What do you think?

**Comment by cormullion** [comment]
While you're at versions < 1.0 it's possible to consider each version as a development or breaking version - I think - https://pkgdocs.julialang.org/v1/compatibility/#compat-pre-1.0 . Perhaps it's useful for people to be able to track/monitor updates and new versions using the standard registry - if they post questions on Discourse the version number might be good information....

**Pull request merged**
